#!/bin/bash

##------------------------------------------------------------------------------
## environment setup
##------------------------------------------------------------------------------
__DEBUG__=1
__RECURSE__=1
##------------------------------------------------------------------------------
## end environment setup
##------------------------------------------------------------------------------



##------------------------------------------------------------------------------
## setting up traps
##------------------------------------------------------------------------------

trap exit_on_signal SIGINT SIGTERM

exit_on_signal() {
    echo "Script interrupted" 2>&1
    exit 1
}

##------------------------------------------------------------------------------
## end setting up trap
##------------------------------------------------------------------------------


declare -a rename_patterns=("y/A-Z/a-z/"
    "s/^([\(\[\{]|[\)\]\}])//g"
    "s/\/([\(\[\{]|[\)\]\}])/\//g"
    "s/([\(\[\{]|[\)\]\}])/./g"
    "s/^\s+//g"
    "s/\/\s+//g"
    "s/\s+/\./g"
    "s/^\_+//g"
    "s/\/\_+//g"
    "s/\_+/\./g"
    "s/^\,+//g"
    "s/\/\,+//g"
    "s/\,+/\./g"
    "s/^\-+//g"
    "s/\/\-+//g"
    "s/\-+/\./g"
    "s/^\=+//g"
    "s/\/\=+//g"
    "s/\=+/\./g"
    "s/~//g"
    "s/&/and/g"
    "s/:/./g"
    "s/\'//g"
    "s/\.+/\./g"
    "s/\.$//g"
    "s/[^\/A-Za-z0-9.+]//g")


##------------------------------------------------------------------------------
## start of functions
##------------------------------------------------------------------------------

function rename_with_patterns() {
    local newName="$1"
    if [[ -z "$newName" ]]; then
        (($__DEBUG__==1)) || echo "argument expected." 1>&2
    else
        (($__DEBUG__==1)) || echo "processing file ${newName} ::"
        for i in "${rename_patterns[@]}"
        do
            (($__DEBUG__==1)) || echo "running pattern :: $i"
            local checkName=$(perl-rename -v "${i}" "$newName")
            if [[ ! -z "$checkName" ]]; then
                newName=${checkName##* -> }
                (($__DEBUG__==1)) || echo "renamed to ... $newName"
            fi
        done
        if [[ ! -z "$2" ]]; then
            eval "$2=${newName}"
        fi
    fi
}


function main() {
    if (( UID == 0 )); then
        echo "you're using way too much priviledge for renaming files. not allowed."
    else
        if [[ -d "$1" ]]; then
            rename_with_patterns "$1" DIR
            if [[ ! -z "$DIR" ]]; then
                if (( $__RECURSE__==0)); then
                    for file in ${DIR}/*; do
                        main "$file"
                    done
                else
                    for file in ${DIR}/*; do
                        rename_with_patterns "$file"
                    done
                fi
            fi
        elif [[ -f "$1" ]]; then
            rename_with_patterns "$1"
        fi
    fi
}


##------------------------------------------------------------------------------
## end of functions
##------------------------------------------------------------------------------

param=$(realpath "$1")
if [[ $2 =~ ^[0-9]+$ ]]; then
    __RECURSE__=$2
fi

if [[ "${param}" == "/" ]]; then
    echo "not going to rename from / .Try somewhere else."
    exit 1
else
    (($__DEBUG__==1)) || echo "RECURSE :: $__RECURSE__"
    main "$param"
fi

exit 0

