#!/bin/bash

dateString=""

if [[ -z $1 ]]; then
    printf "Please enter date and time ...\n\n"
    curdate=$(date +"%Y-%m-%d")
    curtime=$(date +"%H:%M:%S")
    read -ep "Date (YYYY-MM-DD) :: " -i"$curdate" date
    read -ep "Time (HH:MM:SS) :: " -i"$curtime" time
    dateString="$date $time"
else
    dateString="$1";
fi

if [[ ${#dateString} == 19 ]]; then
    date --date "$dateString" >/dev/null 2>&1
    if [[ $? == 0 ]]; then
        sudo hwclock --set --date="$dateString"
        sudo hwclock --hctosys
    else
        printf "Date format not recognized\n"
    fi
else
    printf "Date format not recognized\n"
fi

